language: node_js
node_js:
  - "node"
  - "11"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"

os:
  - linux
  - osx

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - lrzsz
    - socat

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; brew install lrzsz socat; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export CXX=g++-4.9; fi

install:
  - npm install
script:
  - npm test

after_success:
  - ./node_modules/.bin/jscoverage lib lib-cov
  - XMODEM_COV=1 node_modules/.bin/mocha -S --bail --reporter mocha-lcov-reporter --exit | ./node_modules/coveralls/bin/coveralls.js
